version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    container_name: heapvortex-backend
    ports:
      - "8080:8080"
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - RUNNING_IN_DOCKER=true
    volumes:
      # 1. The existing uploads mapping
      - /Users/sameervhatkar/Study/Projects/HeapVortex/uploads:/app/uploads
      # 2. NEW: Map your project folder so Docker can read the Truststore!
      - /Users/sameervhatkar/Study/Projects/HeapVortex:/app/certs
  frontend:
    build:
      context: ./frontend
    container_name: heapvortex-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  heap_data: