#This configuration file was written by: org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser
#Thu Jun 11 11:06:43 UTC 2026
applicationCSSResources=platform\:/plugin/org.eclipse.platform/images/
cssTheme=org.eclipse.e4.ui.css.theme.e4_default
eclipse.application=org.eclipse.mat.ui.rcp.application
eclipse.p2.data.area=@config.dir/../p2
eclipse.p2.profile=DefaultProfile
eclipse.product=org.eclipse.mat.ui.rcp.MemoryAnalyzer
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.framework=file\:plugins/org.eclipse.osgi_3.24.200.v20260515-1403.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
osgi.requiredJavaVersion=21
osgi.splashPath=platform\:/base/plugins/org.eclipse.mat.ui.rcp
