spring.application.name=backend

jmx.host=localhost
jmx.port=9999

# Eclipse MAT CLI Path inside the Linux Docker container
mat.command=/app/mat/mat-headless.sh

# Persistent Upload Directory inside the container (mapped to Docker volume)
heap.upload.directory=/app/uploads
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
